name: docker_build_ActiveMQ

on: workflow_dispatch

jobs:
    build-to-docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
          
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
            username: ${{ secrets.USER_ID }}
            password: ${{ secrets.SECRET_ID }}

      - name: build_image
        run: |
                docker build -t activeMQ .
                docker tag activeMQ:6.1.3 lakulos/activemq:6.1.3
                docker push lakulos/activemq:6.1.3
    
